version: '3'

services:

    app:
        build: .
        container_name: challenge-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        restart: always
        tty: true
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: challenge-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8
        command: --innodb-use-native-aio=0
        container_name: challenge-db
        restart: always
        tty: true
        ports:
            - "33060:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:management
        container_name: "challenge-rabbitmq"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: "local-vh"
        ports:
            - "5673:5672"
            - "15673:15672"
        networks:
            - app-network    

networks:
    app-network:
        driver: bridge            